# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b703bf21294bb04ea2d8776501a3c2b1a383d589c870250caf3fa95e6de56dc1142c20569ddcd17b7f7ad12d91ed0b48711de500855e27169704faa5c1481052

test:
  secret_key_base: 4572aa1f79fa8d8c3f93896f0e41d0e01899f1bb2aba4a6bc9b79ff58d5981579cd59fcaea7438d7398932649fe2fe2f575913ad20014ae8d6353a967a71abf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
