production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>

development:
  secret_key_base: gffjkw9f9irjrnrj324j23j90we09jasdjijIOJAJAWAIJO
  secret_token: rjrnrj324j23j90we09jasdjijIO
